language: php

env:
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer install --dev
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
